dataset:
  name: "cifar100"
  image_size: 32
model:
  type: "vanilla"
  dim: 128
  width_factor: 1
  depth_factor: 1
training:
  projector_features: 512
  sim_coef: 25.0
  std_coef: 25.0
  cov_coef: 1.0
  batch_size: 256
  optimizer_type: "sgd"
  learning_rate: 0.002
  weight_decay: 0.000001
  num_epochs: 1000
  num_workers: 8
fast_dev_run: false
run_id: null
