dataset:
  name: "stl10"
  image_size: 32
model:
  type: "resnet20"
  dim: 128
training:
  projector_features: 512
  sim_coef: 25.0
  std_coef: 25.0
  cov_coef: 1.0
  batch_size: 256
  optimizer_type: "sgd"
  learning_rate: 0.002
  weight_decay: 0.000001
  num_epochs: 1000
  num_workers: 1
fast_dev_run: false
